### ISSUE TITLE
MissingMethodException in ServiceStack.Text.JsConfigScope

### ISSUE THREAD

**Issue by wbrussell** [wwwlicious/servicestack-discovery-consul#29]
Hello,
I'm trying out this plugin and I'm getting this exception on startup using the basic setup outlined in the wiki.  I'm using SS v5.4.0.

> ServiceStack.Discovery.Consul.GatewayServiceDiscoveryException
>   HResult=0x80131500
>   Message=Failed to register the service with consul agent http://127.0.0.1:8500
>   Source=ServiceStack.Discovery.Consul
>   StackTrace:
>    at ServiceStack.Discovery.Consul.ConsulDiscovery.Register(IAppHost appHost)
>    at ServiceStack.Discovery.Consul.ConsulFeature.RegisterService(IAppHost host)
>    at ServiceStack.ServiceStackHost.OnAfterInit()
>    at ServiceStack.Host.HttpListener.HttpListenerBase.OnAfterInit()
>    at Events2HVAC.Analytics.Service.AppHost.OnAfterInit() in E:\Git\events2hvac_v1.5.x\Events2HVAC.Analytics.Service\Events2HVAC.Analytics.Service\AppHost.cs:line 202
>    at ServiceStack.ServiceStackHost.Init()
>    at Events2HVAC.Analytics.Service.Program.Main(String[] args) in E:\Git\events2hvac_v1.5.x\Events2HVAC.Analytics.Service\Events2HVAC.Analytics.Service\Program.cs:line 31
> 
> Inner Exception 1:
> MissingMethodException: Method not found: 'Void ServiceStack.Text.JsConfigScope.set_EmitCamelCaseNames(System.Nullable`1<Boolean>)'.

**Comment by kkankala** [comment]
Is there a workaround for this? I tried on 5.7 and its still an issue.
